const Blockchain = require('./blockchain.js')

const atrium = new Blockchain()
atrium.createNewTransaction(100, 'oscar', 'terry')
const output1 = atrium.proofOfWork(atrium.chain[0]['hash'], atrium.pendingTransactions)
atrium.createNewBlock(output1['nonce'], atrium.chain[0]['hash'], output1['hash'])
atrium.createNewTransaction(1200, 'oscar', 'terry')
atrium.createNewTransaction(1100, 'oscar', 'terry')
const output2 = atrium.proofOfWork(atrium.chain[1]['hash'], atrium.pendingTransactions)
atrium.createNewBlock(output2['nonce'], atrium.chain[0]['hash'], output2['hash'])
console.log(atrium)
console.log(atrium.chain[1].transactions)
console.log(atrium.chain[2].transactions)